name: termo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'
scripts:
  coverage: full_coverage -i *_modules.dart
  check-unused-files: flutter pub run dart_code_metrics:metrics check-unused-files lib > metrics.txt
  analyze: flutter pub run dart_code_metrics:metrics analyze  lib > metrics.txt
  check-unused-code: flutter pub run dart_code_metrics:metrics check-unused-code lib > metrics.txt

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  diacritic: ^0.1.3
  badges: ^2.0.3
  asuka: ^2.0.0+1
  dio: ^4.0.6
  url_launcher: ^6.1.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2

flutter:
  uses-material-design: true
  assets:
    - assets/
