name: termo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
scripts:
  coverage: full_coverage -i *_modules.dart
  check-unused-files: flutter pub run dart_code_metrics:metrics check-unused-files lib > metrics.txt
  analyze: flutter pub run dart_code_metrics:metrics analyze  lib > metrics.txt
  check-unused-code: flutter pub run dart_code_metrics:metrics check-unused-code lib > metrics.txt
  update-goldens: flutter test --update-goldens

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  diacritic: ^0.1.4
  badges: ^3.1.1
  asuka: ^2.2.0
  dio: ^5.3.1
  url_launcher: ^6.1.12
  http: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.0.15
  flutter_modular: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  mockito: ^5.4.3
  build_runner: ^2.1.11
  golden_toolkit: ^0.15.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
