// Mocks generated by Mockito 5.3.2 from annotations
// in termo/test/app/modules/words/presentation/pages/black_list/black_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/widgets.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:termo/app/commons/adapters/custom_alerts/dialog_adapter.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IDialogAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDialogAdapter extends _i1.Mock implements _i2.IDialogAdapter {
  MockIDialogAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showDialog(_i3.Widget? child) => super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [child],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void alertSnackBar(String? text) => super.noSuchMethod(
        Invocation.method(
          #alertSnackBar,
          [text],
        ),
        returnValueForMissingStub: null,
      );
}
